<?php

/**
 * @file
 *
 * A Drupal wrapper for the Yahoo YUI Uploader Widget
 */
define('THEME_YUI_UPLOADER', 'yui_uploader');

/**
 * Implements hook_menu().
 */
function yui_uploader_menu() {
  return  array(
    'yui/uploader/%' => array(
      'file' => 'yui.upload.inc',
      'page callback' => 'yui_uploader_upload_file',
      'page arguments' => array(2),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    )
  );
}

/**
 * Implements hook_elements().
 */
function yui_uploader_elements() {
  return array(
    'yui_uploader' => array(
      '#input' => TRUE,
      '#pre_render' => array('yui_uploader_pre_render'),
      '#process' => array('yui_uploader_process'),
      '#width' => '100px',
      '#height' => '40px',
      '#extensions' => array('*'),
      '#multiple_files' => TRUE,
      '#required' => FALSE
    )
  );
}

/**
 * Implementation of hook_theme().
 */
function yui_uploader_theme() {
  return array(
    THEME_YUI_UPLOADER => array(
      'arguments' => array('element' => NULL)
    )
  );
}

/**
 * Implementation of theme_hook().
 */
function theme_yui_uploader(array $element) {
  _form_set_class($element, array(
    'yui-uploader'
  ));
  $id = $element['#id'];
  $attributes = drupal_attributes($element['#attributes']);
  $markup = <<<EOT
<div id='$id' {$attributes}></div>
<div id="yui-uploader-overall-progress"></div>
<br/>
<div id='yui-uploader-files' style='display:none'>
  <table id='yui-uploader-filenames' style='border-width:1px; border-style:solid; padding:5px;'>
    <thead><tr><th>Filename</th><th>File size</th><th>Percent uploaded</th></tr></thead><tbody></tbody>
  </table>
</div>
EOT;
  return theme('form_element', $element, $markup);
}

/**
 * Implements hook_process().
 */
function yui_uploader_process(array $element, $edit, array &$form_state, array $complete_form = NULL) {
  $element['#form_build_id'] = $complete_form['#build_id'];
  return $element;
}

/**
 * Implements hook_pre_render().
 */
function yui_uploader_pre_render(array $element) {
  module_load_include('inc', 'yui', 'yui.utils');
  $add_prefix = create_function('$a', 'return "*.$a";');
  $extensions = array_map($add_prefix, $element['#extensions']);
  $extensions = implode(';', $extensions);
  $element['#width'];
  $data = array(
    'yui' => array(
      'uploader' => array(
        'select' => '#' .$element['#id'], // Only one supported now.
        'required' => $element['#required'], // Prevent form submission until one or more files have been uploaded.
        'config' => array(
          'selectButtonLabel' => t('Upload Files'),
          'width' => $element['#width'],
          'height' => $element['#height'],
          'fileFilters' => array(array('description' => 'Files', 'extensions' => $extensions)),
          'multipleFiles' => $element['#multiple_files'],
          'swfURL' =>  url(yui_get_assets_file_path('uploader') . '/flashuploader.swf', array('query' => array('t' => rand()))),
          'uploadURL' => url('yui/uploader/' . $element['#form_build_id'])
        )
      )
    )
  );
  yui_add_seed();
  drupal_add_js($data, 'setting');
  drupal_add_js(drupal_get_path('module', 'yui_uploader') . '/js/yui-drupal-uploader.js');
  drupal_add_css(drupal_get_path('module', 'yui_uploader') . '/css/yui-uploader-progress-bar.css');
  return $element;
}